### ISSUE TITLE
Periodic crashes of plasmashell with Plasma 5.10.5

### ISSUE THREAD

**Issue by shmerl** [kotelnik/plasma-applet-weather-widget#60]
I'm using KDE Plasma 5.10.5 in Debian testing, and when weather widget is installed, plasmashell periodically crashes (not very often). Removing the applet makes those crashes stop, that's how I identified the source.

**Comment by shmerl** [comment]
Oh, looks like it reported plasmoid version 1.6.5. Weird, I thought I just installed 1.6.10 before. I just reinstalled it, and it now shows 1.6.10. I'll monitor the crash. Closing for now.

**Comment by shmerl** [comment]
No, it does cause plasmashell crashes even with 1.6.10. Reopening.

**Comment by kotelnik** [comment]
Thanks for report! Is is crashing with OpenWeatherMap provider or yr.no or both?

**Comment by shmerl** [comment]
OpenWeatherMap (and I have only one location using it). After the update it's less common though.

**Comment by shmerl** [comment]
Probably not very useful, but here is a recent crash stack trace from the KDE reporter. Looks like memory allocation related:

```
Application: Plasma (plasmashell), signal: Aborted
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7fbe6cea6900 (LWP 1637))]

Thread 17 (Thread 0x7fbd7ffff700 (LWP 2946)):
#0  0x00007fbe66fdb1c1 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#1  0x00007fbe61333658 in g_main_context_prepare () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fbe6133404b in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbe6133422c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fbe66fdb41b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fbe66f80dba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fbe66da03ca in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fbe66da529d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fbe65f84494 in start_thread (arg=0x7fbd7ffff700) at pthread_create.c:333
#9  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 16 (Thread 0x7fbd84d52700 (LWP 2945)):
[KCrash Handler]
#6  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#7  0x00007fbe6661142a in __GI_abort () at abort.c:89
#8  0x00007fbe6664dc00 in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7fbe66742d78 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#9  0x00007fbe66653fc6 in malloc_printerr (action=3, str=0x7fbe6673f8be "corrupted size vs. prev_size", ptr=<optimized out>, ar_ptr=<optimized out>) at malloc.c:5049
#10 0x00007fbe6665438d in malloc_consolidate (av=av@entry=0x7fbd80000020) at malloc.c:4213
#11 0x00007fbe66655dfa in _int_malloc (av=av@entry=0x7fbd80000020, bytes=bytes@entry=2056) at malloc.c:3488
#12 0x00007fbe66657f64 in __GI___libc_malloc (bytes=2056) at malloc.c:2928
#13 0x00007fbe66a0a098 in operator new(unsigned long) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#14 0x00007fbe66dfeaeb in QHashData::rehash(int) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fbd8504d3b9 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XmlPatterns.so.5
#16 0x00007fbd84e4773e in QXmlNamePool::QXmlNamePool() () from /usr/lib/x86_64-linux-gnu/libQt5XmlPatterns.so.5
#17 0x00007fbd84e48ba6 in QXmlQuery::QXmlQuery() () from /usr/lib/x86_64-linux-gnu/libQt5XmlPatterns.so.5
#18 0x00007fbd8516d225 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#19 0x00007fbd8516e715 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#20 0x00007fbd8516f306 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#21 0x00007fbd8516f35d in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#22 0x00007fbe67f8746c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007fbe67f8ed34 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007fbe66f82d68 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007fbe66f854dd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007fbe66fdbdd3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007fbe61333f67 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007fbe613341a0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007fbe6133422c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007fbe66fdb3ff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007fbe66f80dba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007fbe66da03ca in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x00007fbd8516f3c5 in ?? () from /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/XmlListModel/libqmlxmllistmodelplugin.so
#34 0x00007fbe66da529d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#35 0x00007fbe65f84494 in start_thread (arg=0x7fbd84d52700) at pthread_create.c:333
#36 0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 15 (Thread 0x7fbdae447700 (LWP 2851)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe404b1bdb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fbe404b1af7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbdae447700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 14 (Thread 0x7fbdb3e73700 (LWP 2850)):
#0  0x00007fbe666bc66d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fbe61334119 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fbe6133422c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbe66fdb41b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007fbe66f80dba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fbe66da03ca in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fbe6aaaf846 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5
#7  0x00007fbe66da529d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fbe65f84494 in start_thread (arg=0x7fbdb3e73700) at pthread_create.c:333
#9  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 13 (Thread 0x7fbdb4674700 (LWP 2797)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe404b1bdb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fbe404b1af7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbdb4674700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 12 (Thread 0x7fbdb4e75700 (LWP 2796)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe404b1bdb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fbe404b1af7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbdb4e75700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 11 (Thread 0x7fbdb5676700 (LWP 2795)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe404b1bdb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fbe404b1af7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbdb5676700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 10 (Thread 0x7fbdb5e77700 (LWP 2794)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe404b1bdb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fbe404b1af7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbdb5e77700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 9 (Thread 0x7fbdb6678700 (LWP 2793)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe404b1bdb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fbe404b1af7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbdb6678700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 8 (Thread 0x7fbdb70b3700 (LWP 2792)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe404b1bdb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fbe404b1af7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbdb70b3700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 7 (Thread 0x7fbdb78b4700 (LWP 2791)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe404b1bdb in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#2  0x00007fbe404b1af7 in ?? () from /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbdb78b4700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 6 (Thread 0x7fbe42dad700 (LWP 2790)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fbe6c780634 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Script.so.5
#2  0x00007fbe6c780679 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Script.so.5
#3  0x00007fbe65f84494 in start_thread (arg=0x7fbe42dad700) at pthread_create.c:333
#4  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 5 (Thread 0x7fbe4cf5a700 (LWP 2776)):
#0  0x00007fbe61334201 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#1  0x00007fbe66fdb41b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#2  0x00007fbe66f80dba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#3  0x00007fbe66da03ca in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007fbe69f16de5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#5  0x00007fbe66da529d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fbe65f84494 in start_thread (arg=0x7fbe4cf5a700) at pthread_create.c:333
#7  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 4 (Thread 0x7fbe4f1cc700 (LWP 1838)):
#0  0x00007fbe666b86dd in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fbe61378230 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fbe61333bfb in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbe613340c0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fbe6133422c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fbe66fdb41b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fbe66f80dba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fbe66da03ca in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fbe69f16de5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5
#9  0x00007fbe66da529d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fbe65f84494 in start_thread (arg=0x7fbe4f1cc700) at pthread_create.c:333
#11 0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 3 (Thread 0x7fbe54c21700 (LWP 1676)):
#0  0x00007fbe666b86dd in read () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fbe61378230 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fbe61333bfb in g_main_context_check () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbe613340c0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007fbe6133422c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007fbe66fdb41b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fbe66f80dba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007fbe66da03ca in QThread::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fbe67bbee45 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#9  0x00007fbe66da529d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fbe65f84494 in start_thread (arg=0x7fbe54c21700) at pthread_create.c:333
#11 0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 2 (Thread 0x7fbe56c89700 (LWP 1675)):
#0  0x00007fbe666bc66d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fbe6b6bb150 in ?? () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007fbe6b6bcee9 in xcb_wait_for_event () from /usr/lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007fbe589cef09 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007fbe66da529d in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fbe65f84494 in start_thread (arg=0x7fbe56c89700) at pthread_create.c:333
#6  0x00007fbe666c5abf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:97

Thread 1 (Thread 0x7fbe6cea6900 (LWP 1637)):
#0  0x00007fbe666bc66d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x00007fbe61334119 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007fbe6133422c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007fbe66fdb3ff in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007fbe66f80dba in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fbe66f89d24 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x000055b927a8acc2 in ?? ()
#7  0x00007fbe665fd2e1 in __libc_start_main (main=0x55b927a8a160, argc=1, argv=0x7ffd130b53c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd130b53b8) at ../csu/libc-start.c:291
#8  0x000055b927a8b03a in _start ()
```

**Comment by kotelnik** [comment]
Thanks! I have a few of my own, too. And all of them including this one has "QXmlQuery" and "XmlListModel" as a common aspect. If I don't manage to create minimal case for Qt bug report, I'll file it anyway with some of the stack traces.

**Comment by kotelnik** [comment]
I was unable to create a nice little app to replicate the issue, but I've filed the Qt bug anyway:
https://bugreports.qt.io/browse/QTBUG-63647

**Comment by kotelnik** [comment]
It is over a week since Qt upgrade 5.9.1 -> 5.9.2 and I didn't notice any crash. Do you @shmerl or somebody else has a crash experience with Qt 5.9.2?

**Comment by shmerl** [comment]
5.9.2 didn't roll into Debian testing yet (and for now I simply disabled the applet to avoid crashes). Once it does, I'll re-enable it, and will let you know how it goes!

**Comment by shmerl** [comment]
Just tested with Qt 5.9.2 in Debian testing, I'm still getting crashes (widget 1.6.10).

**Comment by shmerl** [comment]
Interestingly, with one source that I'm using there aren't any crashes. I suppose some sources feed broken XML. May be applying some XML sanitizing prior to parsing can be a workaround.

**Comment by kotelnik** [comment]
Thanks for your testing! I'm still unable to replicate that with multiple locations. I even localy reverted some commits that made the crashing less frequent. But the crashing is obviously random, so it is possible that I have just a big luck.
Anyway, I was asking because I wanted to mark the Qt ticket as resolved. Now I know that I will not do that until they fix it and you say it is not crashing anymore :).

**Comment by shmerl** [comment]
I've been using it for a while, and it wasn't crashing.

**Comment by kotelnik** [comment]
That's good news! So there is a possibility that Qt 5.9.2+ fixed the issue? Anybody else who experiences the crashing and has Qt 5.9.2+, please, speak up! :) I'll wait a week or two and then close this issue as well as Qt jira ticket. Thanks!

**Comment by pierremoreau** [comment]
I used to have crashes, until I updated to Qt 5.9.2. Haven’t seen a single one since. :-)

**Comment by shmerl** [comment]
Yes, I suspect it was one of the minor Qt updates. I have now:

5.9.2-3  / 5.9.2+dfsg-6 (in Debian terms).
